dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install pycodestyle"
# command to run tests
script:
  # Tests
  - python setup.py test
  - pycodestyle tableauserverclient test samples
